[project]
name = "ehentaiautosignin"
version = "0.1.0"
description = "Auto Sign In for E-Hentai"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "requests>=2.32.4",
    "urllib3>=2.5.0",
]
